version: "3.9"
services:
    db:
        container_name: db_server
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'vital_signs'
            MYSQL_ROOT_PASSWORD: 'alsharif_2022'
    app:
        container_name: rasa_app
        restart: always
        links:
            - db
        build: ./
        ports:
            - "5001:5000"
        depends_on:
            - db
